config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :halls
  resources :movies
  resources :shows, except: [:edit, :update] do
    resources :reservations, only: [:index, :show, :new, :create] do
      patch 'confirm', on: :member
      patch 'cancel', on: :member
    end
  end
  root to: 'shows#index'
end

app/models/hall.rb
# frozen_string_literal: true

class Hall < ApplicationRecord
  has_many :shows, dependent: :destroy

  scope :sorted_alphabetically, -> { order(:name) }
end

app/controllers/halls_controller.rb
# frozen_string_literal: true

class HallsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    @halls = authorize Hall.all
  end

  def show
    authorize find_hall
  end

  def new
    @hall = authorize Hall.new
  end

  def create
    @hall = authorize Hall.new
    result = HallContract.new(hall: @hall).call(params[:hall].to_unsafe_h)
    @hall.attributes = result.to_h

    if result.success?
      @hall.save
      redirect_to @hall
    else
      @errors = result.errors(full: true)
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize find_hall
  end

  def update
    authorize find_hall
    result = HallContract.new(hall: @hall).call(params[:hall].to_unsafe_h)
    @hall.attributes = result.to_h

    if result.success?
      @hall.save
      redirect_to @hall
    else
      @errors = result.errors(full: true)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize find_hall

    @hall.destroy

    redirect_to halls_path, status: :see_other
  end

  private

  def find_hall
    @hall = Hall.find(params[:id])
  end
end

app/views/halls/_form.html.erb
<%= form_with model: hall do |form| %>
  <div>
    <div><%= form.label :name %></div>
    <div><%= form.text_field :name %></div>
  </div>
  <div>
    <div><%= form.label :capacity %></div>
    <div><%= form.number_field :capacity, min: 1 %></div>
  </div>
  <div>
    <% errors&.any? do |error| %>
      <%= error.text %>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/halls/edit.html.erb
<h1>Edit hall</h1>

<%= render "form", hall: @hall, errors: @errors %>

app/views/halls/index.html.erb
<h1>Halls</h1>

<ul>
  <% @halls.each do |hall| %>
    <li><%= link_to hall.name, hall %></li>
  <% end %>
</ul>

<% if policy(@halls).new? %>
  <div><%= link_to "Add new hall", new_hall_path %></div>
<% end %>

<div><%= link_to "Back", shows_path %></div>

app/views/halls/new.html.erb
<h1>Add new hall</h1>

<%= render "form", hall: @hall, errors: @errors %>

app/views/halls/show.html.erb
<h1>Hall "<%= @hall.name %>"</h1>
<p>Number of seats: <%= @hall.capacity %></p>

<% if policy(@hall).edit? %>
  <div><%= link_to "Edit", edit_hall_path(@hall) %></div>
<% end %>

<% if policy(@hall).destroy? %>
  <div><%= link_to "Delete", hall_path(@hall), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></div>
<% end %>

<div><%= link_to "Back", halls_path %></div>