config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :halls
  resources :movies
  resources :shows, except: [:edit, :update] do
    resources :reservations, only: [:index, :show, :new, :create] do
      patch 'confirm', on: :member
      patch 'cancel', on: :member
    end
  end
  root to: 'shows#index'
end

app/models/show.rb
# frozen_string_literal: true

class Show < ApplicationRecord
  belongs_to :hall
  belongs_to :movie
  has_many :reservations, dependent: :destroy

  validates :start_time, presence: true
  validates :start_time, comparison: { greater_than: Time.zone.now }

  scope :today_shows, lambda { |movie|
    where(movie:)
    .where(start_time: (Time.zone.now..Time.zone.now.end_of_day))
    .order(:start_time)
  }

  def end_time
    start_time + movie.length_in_minutes.minutes + ADS_TIME
  end

  def time_period
    start_time..end_time
  end
end

app/controllers/shows_controller.rb
# frozen_string_literal: true

class ShowsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    authorize Show
    @movies = Movie.all
    @reservations = Reservation.relevant_for(current_user) if current_user&.customer?
  end

  def show
    authorize find_show
  end

  def new
    @show = authorize Show.new
  end

  def create
    @show = authorize Show.new(show_params)

    if @show.valid? && TimePeriodDoesntOverlap.validate(@show)
      @show.save
      redirect_to @show
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    authorize find_show

    @show.destroy

    redirect_to shows_path, status: :see_other
  end

  private

  def show_params
    params.require(:show).permit(:hall_id, :movie_id, :start_time)
  end

  def find_show
    @show = Show.find(params[:id])
  end
end

app/views/shows/_form.html.erb
<%= form_with model: show do |form| %>
  <div>
    <div><%= form.label :hall_id %></div>
    <div>
      <%= form.collection_select :hall_id, Hall.sorted_alphabetically, :id, :name, prompt: "Please select hall" %>
    </div>
  </div>
   <div>
    <div><%= form.label :movie_id %></div>
    <div>
      <%= form.collection_select :movie_id, Movie.sorted_alphabetically, :id, :title, prompt: "Please select movie" %>
    </div>
  </div>
  <div>
    <div><%= form.label :start_time %></div>
    <div>
      <%= form.datetime_local_field :start_time %>
    </div>
  </div>
  <div>
    <% show.errors.any? do |error| %>
      <%= error.full_message %>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shows/index.html.erb
<h1>Today Shows</h1>

<% if current_user&.customer? %>
  <% if @reservations.count == 0 %>
    <h2>No Reservations</h2>
    <p>We hope you change your mind and see something that's incredible very soon!</p>
  <% else %>
    <h2>My Reservations</h2>
    <div>
      <ol>
        <% @reservations.each do |reservation| %>
          <li>
            <%= 
              link_to "#{reservation.show.movie.title} -> #{formatted_datetime reservation.show.start_time}",
              show_reservation_path(show_id: reservation.show.id, id: reservation.id) 
            %>
          </li>
        <% end %>
      </ol>
    </div>
  <% end %>
<% end %>

<div>
  <% @movies.each do |movie| %>
  <h1><%= movie.title %></h1>
  <ul>
    <% Show.today_shows(movie).each do |show| %>
      <li>
        <%= link_to formatted_time(show.start_time), show %>
        <% if policy(Reservation).index? %>
          | <%= link_to "Reservations", show_reservations_path(show_id: show.id) %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>
</div>

<% if policy(Show).new? %>
  <div><%= link_to "Add new show", new_show_path %></div>
<% end %>

<div><%= link_to "See all movies", movies_path %></div>
<div><%= link_to "See all halls", halls_path %></div>

app/views/shows/new.html.erb
<h1>Add new show</h1>

<%= render "form", show: @show %>

app/views/shows/show.html.erb
<h1><%= @show.movie.title %></h1>

<div>
  Movie will be played inside of hall "<%= @show.hall.name %>",
  starting at <%= formatted_time @show.start_time %> and ending
  around <%= formatted_time @show.end_time %>.
</div>

<div><%= link_to "Make reservation", new_show_reservation_path(@show) %></div>

<% if policy(@show).destroy? %>
  <div><%= link_to "Delete", show_path(@show), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></div>
<% end %>

<div><%= link_to "Back", shows_path %></div>